/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDo;
import java.io.File;
import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "ToDo List Manager";
    }
    public static void main(String[] args) {
        String input = mainScreenDisplay();
        switch (input) {
            case "1":
//                Open ToDo List
                System.out.println(input + " was returned");
                break;
            case "2":
//                Display ToDo List
                System.out.println(input + " was returned");
                try {
                    displayToDoList();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                break;
            case "3":
//                Add a ToDo List
                System.out.println(input + " was returned");
                break;
            case "4":
//                Edit ToDo List
                System.out.println(input + " was returned");
                break;
            case "5":
//                Delete ToDo List
                System.out.println(input + " was returned");
                break;
            case "6":
//                Save ToDo List
                System.out.println(input + " was returned");
                break;
            case "7":
//                Exit
                System.out.println(input + " was returned");
                break;
        }
    }
    public static String mainScreenDisplay() {
        Scanner s = new Scanner(System.in);
        System.out.println("                          Main Menu");
        System.out.println("\n");
        System.out.println("1.  Open ToDo List");
        System.out.println("2.  Display ToDo List");
        System.out.println("3.  Add a ToDo List");
        System.out.println("4.  Edit ToDo List");
        System.out.println("5.  Delete ToDo List");2
        System.out.println("6.  Save ToDo List");
        System.out.println("7.  Exit");
        System.out.println("\n");
        System.out.println("Select Option");
        String u = s.nextLine();
        return u;
    }

    public static void displayToDoList() throws Exception {
        File file = new File("C:\\Users\\k330620\\Documents\\Java_class\\JavaGettingStarted_ToDoList\\app\\src\\main\\java\\ToDo\\ToDoList.txt");
        Scanner sc = new Scanner(file);
        StringBuffer sb = new StringBuffer();
        while (sc.hasNext()) {
            sb.append(" " + sc.nextLine());
        }
        System.out.println(sb);
    }
}